
# Create px4 base environment plus rust support

FROM px4_base 
MAINTAINER Todd Stellanova <todd@droneflow.com>

ENV DEBIAN_FRONTEND noninteractive

# install toolchain
RUN curl https://sh.rustup.rs -sSf | \
    sh -s -- --default-toolchain nightly -y

CMD ["/bin/bash"]


