
# Perform px4_sitl build on aarch64

FROM px4_base 
MAINTAINER Todd Stellanova <todd@droneflow.com>

ENV DEBIAN_FRONTEND noninteractive


COPY ./entrypoint-build.sh /
RUN chmod +x ./entrypoint-build.sh 
ENTRYPOINT ["./entrypoint-build.sh"]

