
# Perform px4_sitl build on aarch64 of uorb-sidecar

FROM px4_base_rust 
MAINTAINER Todd Stellanova <todd@droneflow.com>

ENV DEBIAN_FRONTEND noninteractive


COPY ./entrypoint-sitl-uorb-build.sh /
RUN chmod +x ./entrypoint-sitl-uorb-build.sh 
ENTRYPOINT ["./entrypoint-sitl-uorb-build.sh"]

