
# Perform px4_sitl build on aarch64

FROM px4_base_rust 

MAINTAINER Todd Stellanova <todd@droneflow.com>

ENV DEBIAN_FRONTEND noninteractive


COPY ./entrypoint-sitl-mavlink-build.sh /
RUN chmod +x ./entrypoint-sitl-mavlink-build.sh 
ENTRYPOINT ["./entrypoint-sitl-mavlink-build.sh"]

